version: "3.9"

services:
  app:
    image: autoeasy
    build: ./client
    ports:
      - "3000:3000"

  server:
    container_name: backend
    image: backend
    build: ./server
    ports:
     - "8000:8000"